from __future__ import annotations
from typing import Any

class RuntimeSession:
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def from_floating_license_id(floating_license_id: Any, include_pro: Any = True, fallback_tier: Any = 'open', provider_url: Any = None, machine_id: Any = None, customer_id: Any = None) -> Any: ...
    def from_signed_entitlement_json(signed_entitlement_json: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
    def list_tools(self) -> Any: ...
    def list_tools_json(self) -> Any: ...
    def run_tool(self, tool_id: Any, args: Any) -> Any: ...
    def run_tool_json(self, tool_id: Any, args_json: Any) -> Any: ...
    def run_tool_json_stream(self, tool_id: Any, args_json: Any, callback: Any) -> Any: ...
    def run_tool_json_with_progress(self, tool_id: Any, args_json: Any) -> Any: ...
    def run_tool_stream(self, tool_id: Any, args: Any, callback: Any) -> Any: ...

class Raster:
    @property
    def active_band(self) -> int: ...
    @property
    def band_count(self) -> int: ...
    @property
    def file_name(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    def __abs__(self) -> Any: ...
    def __add__(self, value: Any) -> Any: ...
    def __and__(self, value: Any) -> Any: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __iadd__(self, value: Any) -> Any: ...
    def __idiv__(self, other: Any) -> Any: ...
    def __imul__(self, value: Any) -> Any: ...
    def __invert__(self) -> Any: ...
    def __isub__(self, value: Any) -> Any: ...
    def __itruediv__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __mul__(self, value: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __or__(self, value: Any) -> Any: ...
    def __pos__(self) -> Any: ...
    def __pow__(self, value: Any, mod: Any = None) -> Any: ...
    def __radd__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __rmul__(self, value: Any) -> Any: ...
    def __rpow__(self, value: Any, mod: Any = None) -> Any: ...
    def __rsub__(self, value: Any) -> Any: ...
    def __rtruediv__(self, value: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...
    def __str__(self) -> Any: ...
    def __sub__(self, value: Any) -> Any: ...
    def __truediv__(self, value: Any) -> Any: ...
    def __xor__(self, value: Any) -> Any: ...
    @staticmethod
    def from_numpy(array: Any, base: Any, output_path: Any = None, band: Any = None) -> Any: ...
    def abs(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def acos(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def acosh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def add(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def add_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def and_(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def arccos(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def arcsin(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def arctan(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def asin(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def asinh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def atan(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def atan2(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def atanh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def band(self, band: Any) -> Any: ...
    def calculate_clip_values(self, percent: Any) -> Any: ...
    def calculate_mean(self) -> Any: ...
    def calculate_mean_and_stdev(self) -> Any: ...
    def cbrt(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ceil(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def clamp(self, min_value: Any, max_value: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def clear_crs(self) -> Any: ...
    def configs(self) -> RasterConfigs: ...
    def metadata(self) -> RasterConfigs: ...
    def cos(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def cosh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def crs_epsg(self, strict: Any = False) -> Any: ...
    def crs_wkt(self) -> Any: ...
    def decrement(self, row: Any, column: Any, value: Any, band: Any = None) -> Any: ...
    def decrement_row_data(self, row: Any, values: Any, band: Any = None) -> Any: ...
    def deep_copy(self) -> Any: ...
    def degrees(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def div(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def div_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def divide(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def eq(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def eq_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def exp(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def exp2(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def expm1(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def floor(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ge(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ge_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def get_column_from_x(self, x: Any) -> Any: ...
    def get_data_size_in_bytes(self) -> Any: ...
    def get_file_extension(self) -> Any: ...
    def get_row_data(self, row: Any, band: Any = None) -> Any: ...
    def get_row_from_y(self, y: Any) -> Any: ...
    def get_short_filename(self) -> Any: ...
    def get_value(self, row: Any, column: Any, band: Any = None) -> Any: ...
    def get_x_from_column(self, column: Any) -> Any: ...
    def get_y_from_row(self, row: Any) -> Any: ...
    def gt(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def gt_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def increment(self, row: Any, column: Any, value: Any, band: Any = None) -> Any: ...
    def increment_row_data(self, row: Any, values: Any, band: Any = None) -> Any: ...
    def is_cell_nodata(self, row: Any, col: Any, band: Any = None) -> Any: ...
    def is_finite(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def is_infinite(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def is_memory_backed(self) -> Any: ...
    def is_nan(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def is_nodata(self, output_path: Any = None) -> Any: ...
    def le(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def le_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ln(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def log10(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def log1p(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def log2(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_and(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_and_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_not(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_not_in_place(self, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_or(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_or_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_xor(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def logical_xor_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def lt(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def lt_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def max(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def min(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def mul(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def mul_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def multiply(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ne(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def ne_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def neg(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def new_from_other(other: Any, data_type: Any = None) -> Any: ...
    def new_from_other_with_data(other: Any, data_type: Any = None) -> Any: ...
    def normalize(self, output_path: Any = None) -> Any: ...
    def not_(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def num_cells(self) -> Any: ...
    def num_valid_cells(self) -> Any: ...
    def or_(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def pow(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def pow_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def power(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def radians(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def recip(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def reinitialize_values(self, value: Any) -> Any: ...
    def reproject(self, dst_epsg: Any, output_path: Any = None, callback: Any = None, resample: Any = 'nearest', cols: Any = None, rows: Any = None, extent: Any = None, x_res: Any = None, y_res: Any = None, snap_x: Any = None, snap_y: Any = None, nodata_policy: Any = 'partial_kernel', antimeridian_policy: Any = 'auto', grid_size_policy: Any = 'expand', destination_footprint: Any = 'none') -> Any: ...
    def reproject_bilinear(self, dst_epsg: Any, output_path: Any = None, callback: Any = None) -> Any: ...
    def reproject_nearest(self, dst_epsg: Any, output_path: Any = None, callback: Any = None) -> Any: ...
    def reproject_to_match_grid(self, target_grid: Any, output_path: Any = None, resample: Any = 'nearest', callback: Any = None) -> Any: ...
    def reproject_to_match_resolution(self, reference_grid: Any, output_path: Any = None, resample: Any = 'nearest', callback: Any = None) -> Any: ...
    def reproject_to_match_resolution_in_epsg(self, dst_epsg: Any, reference_grid: Any, output_path: Any = None, resample: Any = 'nearest', callback: Any = None) -> Any: ...
    def round(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def set_crs_epsg(self, epsg: Any) -> Any: ...
    def set_crs_wkt(self, wkt: Any) -> Any: ...
    def set_row_data(self, row: Any, values: Any, band: Any = None) -> Any: ...
    def set_value(self, row: Any, column: Any, value: Any, band: Any = None) -> Any: ...
    def signum(self, output_path: Any = None) -> Any: ...
    def sin(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def sinh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def size_of(self) -> Any: ...
    def sqrt(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def square(self, output_path: Any = None, callback: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def sub(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def sub_in_place(self, other: Any, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def subtract(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def tan(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def tanh(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def to_degrees(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def to_numpy(self, band: Any = None, dtype: Any = None, all_bands: Any = False) -> Any: ...
    def to_radians(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def trunc(self, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...
    def update_min_max(self) -> Any: ...
    def xor_(self, other: Any, output_path: Any = None, band_mode: Any = 'all', bands: Any = None) -> Any: ...

class RasterConfigs:
    @property
    def columns(self) -> int: ...
    @property
    def east(self) -> float: ...
    @property
    def epsg_code(self) -> int: ...
    @property
    def maximum(self) -> float: ...
    @property
    def minimum(self) -> float: ...
    @property
    def nodata(self) -> float: ...
    @property
    def north(self) -> float: ...
    @property
    def resolution_x(self) -> float: ...
    @property
    def resolution_y(self) -> float: ...
    @property
    def rows(self) -> int: ...
    @property
    def south(self) -> float: ...
    @property
    def west(self) -> float: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class VectorMetadata:
    @property
    def attribute_field_names(self) -> list[str]: ...
    @property
    def crs_epsg(self) -> int | None: ...
    @property
    def crs_wkt(self) -> str | None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def feature_count(self) -> int | None: ...
    @property
    def file_name(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def file_size_bytes(self) -> int | None: ...
    @property
    def last_modified_unix_seconds(self) -> float | None: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class LidarMetadata:
    @property
    def crs_epsg(self) -> int | None: ...
    @property
    def crs_wkt(self) -> str | None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def file_name(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def file_size_bytes(self) -> int | None: ...
    @property
    def last_modified_unix_seconds(self) -> float | None: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class Bundle:
    @property
    def bundle_root(self) -> str: ...
    @property
    def family(self) -> str: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def acquisition_datetime_utc(self) -> Any: ...
    def acquisition_mode(self) -> Any: ...
    def cloud_cover_percent(self) -> Any: ...
    def collection_number(self) -> Any: ...
    def incidence_angle_far_deg(self) -> Any: ...
    def incidence_angle_near_deg(self) -> Any: ...
    def list_asset_keys(self) -> Any: ...
    def list_aux_keys(self) -> Any: ...
    def list_band_keys(self) -> Any: ...
    def list_measurement_keys(self) -> Any: ...
    def list_qa_keys(self) -> Any: ...
    def look_direction(self) -> Any: ...
    def metadata_json(self) -> Any: ...
    def mission(self) -> Any: ...
    def off_nadir_angle_deg(self) -> Any: ...
    def orbit_direction(self) -> Any: ...
    def path_row(self) -> Any: ...
    def pixel_spacing_azimuth_m(self) -> Any: ...
    def pixel_spacing_range_m(self) -> Any: ...
    def polarization(self) -> Any: ...
    def polarizations(self) -> Any: ...
    def processing_baseline(self) -> Any: ...
    def processing_level(self) -> Any: ...
    def product_type(self) -> Any: ...
    def read_asset(self, key: Any) -> Any: ...
    def read_aux_layer(self, key: Any) -> Any: ...
    def read_band(self, key: Any) -> Any: ...
    def read_measurement(self, key: Any) -> Any: ...
    def read_qa_layer(self, key: Any) -> Any: ...
    def true_colour_composite(self, wbe: Any, output_path: Any = None, callback: Any = None) -> Any: ...
    def false_colour_composite(self, wbe: Any, output_path: Any = None, callback: Any = None) -> Any: ...
    def scene_id(self) -> Any: ...
    def spatial_bounds(self) -> Any: ...
    def sun_azimuth_deg(self) -> Any: ...
    def sun_elevation_deg(self) -> Any: ...
    def sun_zenith_deg(self) -> Any: ...
    def tile_id(self) -> Any: ...
    def view_angle_deg(self) -> Any: ...

class Vector:
    @property
    def file_name(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def absolute_path(self) -> Any: ...
    def add_field(self, name: Any, field_type: Any = 'text', nullable: Any = True, width: Any = 0, precision: Any = 0, default_value: Any = None) -> Any: ...
    def add_attribute_field(self, name: Any, field_type: Any = 'text', nullable: Any = True, width: Any = 0, precision: Any = 0, default_value: Any = None) -> Any: ...
    def attribute(self, feature_index: Any, field_name: Any) -> Any: ...
    def attribute_field_names(self) -> Any: ...
    def attribute_fields(self) -> Any: ...
    def attributes(self, feature_index: Any) -> Any: ...
    def clear_crs(self) -> Any: ...
    def crs_epsg(self, strict: Any = False) -> Any: ...
    def crs_wkt(self) -> Any: ...
    def deep_copy(self, output_path: Any = None) -> Any: ...
    def exists(self) -> Any: ...
    def feature_count(self) -> Any: ...
    def get_attribute(self, feature_index: Any, field_name: Any) -> Any: ...
    def get_attributes(self, feature_index: Any) -> Any: ...
    def get_file_extension(self) -> Any: ...
    def get_file_size_in_bytes(self) -> Any: ...
    def get_last_modified_unix_seconds(self) -> Any: ...
    def get_short_filename(self) -> Any: ...
    def metadata(self) -> VectorMetadata: ...
    def parent_directory(self) -> Any: ...
    def reproject(self, dst_epsg: Any, output_path: Any = None, callback: Any = None, failure_policy: Any = 'error', antimeridian_policy: Any = 'keep', max_segment_length: Any = None, topology_policy: Any = 'none') -> Any: ...
    def set_attribute(self, feature_index: Any, field_name: Any, value: Any) -> Any: ...
    def set_attributes(self, feature_index: Any, values: Any) -> Any: ...
    def set_crs_epsg(self, epsg: Any) -> Any: ...
    def set_crs_wkt(self, wkt: Any) -> Any: ...
    def schema(self) -> Any: ...
    def update_attribute(self, feature_index: Any, field_name: Any, value: Any) -> Any: ...
    def update_attributes(self, feature_index: Any, values: Any) -> Any: ...

class Lidar:
    @property
    def file_name(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def absolute_path(self) -> Any: ...
    def clear_crs(self) -> Any: ...
    def crs_epsg(self, strict: Any = False) -> Any: ...
    def crs_wkt(self) -> Any: ...
    def deep_copy(self, output_path: Any = None) -> Any: ...
    def exists(self) -> Any: ...
    def get_file_extension(self) -> Any: ...
    def get_file_size_in_bytes(self) -> Any: ...
    def get_last_modified_unix_seconds(self) -> Any: ...
    def get_short_filename(self) -> Any: ...
    def metadata(self) -> LidarMetadata: ...
    def parent_directory(self) -> Any: ...
    def reproject(self, dst_epsg: Any, output_path: Any = None, callback: Any = None, use_3d_transform: Any = False, failure_policy: Any = 'error') -> Any: ...
    def set_crs_epsg(self, epsg: Any) -> Any: ...
    def set_crs_wkt(self, wkt: Any) -> Any: ...

class WbEnvironment:
    @property
    def conversion(self) -> WbConversionCategory: ...
    @property
    def geomorphometry(self) -> WbGeomorphometryDomain: ...
    @property
    def hydrology(self) -> WbHydrologyCategory: ...
    @property
    def lidar_tools(self) -> WbLidarToolsCategory: ...
    @property
    def max_procs(self) -> int: ...
    @property
    def other(self) -> WbOtherCategory: ...
    @property
    def precision_agriculture(self) -> WbPrecisionAgricultureDomain: ...
    @property
    def raster_tools(self) -> WbRasterToolsCategory: ...
    @property
    def remote_sensing(self) -> WbRemoteSensingDomain: ...
    @property
    def terrain(self) -> WbTerrainCategory: ...
    @property
    def topology(self) -> WbTopologyCategory: ...
    @property
    def vector_tools(self) -> WbVectorToolsCategory: ...
    @property
    def verbose(self) -> bool: ...
    @property
    def working_directory(self) -> str: ...

    @staticmethod
    def from_floating_license_id(floating_license_id: Any, include_pro: Any = True, fallback_tier: Any = 'open', provider_url: Any = None, machine_id: Any = None, customer_id: Any = None) -> Any: ...
    @staticmethod
    def from_signed_entitlement_file(entitlement_file: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
    @staticmethod
    def from_signed_entitlement_json(signed_entitlement_json: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...

    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

    def version(self) -> str: ...
    def license_type(self) -> str: ...
    def license_info(self) -> str: ...

    def list_tools(self) -> list[str]: ...
    def categories(self) -> list[str]: ...
    def category(self, name: Any) -> WbToolCategory: ...
    def domain_namespaces(self) -> list[str]: ...
    def domain(self, name: Any) -> WbDomainNamespace: ...
    def describe_tool(self, tool_id: Any, include_locked: Any = False) -> Any: ...
    def search_tools(self, query: Any, include_locked: Any = False) -> Any: ...
    def list_tools_detailed(self, include_locked: Any = False) -> Any: ...

    def read_raster(self, file_name: Any) -> Raster: ...
    def read_vector(self, file_name: Any) -> Vector: ...
    def read_lidar(self, file_name: Any, file_mode: Any = 'r') -> Lidar: ...
    def read_rasters(self, file_names: Any, parallel: Any = True) -> Any: ...
    def read_vectors(self, file_names: Any, parallel: Any = True) -> Any: ...
    def read_lidars(self, file_names: Any, parallel: Any = True) -> Any: ...

    def read_bundle(self, bundle_root: Any) -> Bundle: ...
    def read_landsat(self, bundle_root: Any) -> Bundle: ...
    def read_sentinel2(self, safe_root: Any) -> Bundle: ...
    def read_sentinel1(self, safe_root: Any) -> Bundle: ...
    def read_planetscope(self, bundle_root: Any) -> Bundle: ...
    def read_iceye(self, bundle_root: Any) -> Bundle: ...
    def read_dimap(self, bundle_root: Any) -> Bundle: ...
    def read_maxar_worldview(self, bundle_root: Any) -> Bundle: ...
    def read_radarsat2(self, bundle_root: Any) -> Bundle: ...
    def read_rcm(self, bundle_root: Any) -> Bundle: ...
    def true_colour_composite(self, bundle_root: Any, output_path: Any = None, callback: Any = None) -> Any: ...
    def false_colour_composite(self, bundle_root: Any, output_path: Any = None, callback: Any = None) -> Any: ...

    def reproject_raster(self, input: Any, dst_epsg: Any, output_path: Any = None, callback: Any = None, resample: Any = 'nearest', cols: Any = None, rows: Any = None, extent: Any = None, x_res: Any = None, y_res: Any = None, snap_x: Any = None, snap_y: Any = None, nodata_policy: Any = 'partial_kernel', antimeridian_policy: Any = 'auto', grid_size_policy: Any = 'expand', destination_footprint: Any = 'none') -> Any: ...
    def reproject_vector(self, input: Any, dst_epsg: Any, output_path: Any = None, callback: Any = None, failure_policy: Any = 'error', antimeridian_policy: Any = 'keep', max_segment_length: Any = None, topology_policy: Any = 'none') -> Any: ...
    def reproject_lidar(self, input: Any, dst_epsg: Any, output_path: Any = None, callback: Any = None, use_3d_transform: Any = False, failure_policy: Any = 'error') -> Any: ...
    def reproject_rasters(self, inputs: Any, dst_epsg: Any, output_paths: Any = None, parallel: Any = True, callback: Any = None) -> Any: ...
    def reproject_vectors(self, inputs: Any, dst_epsg: Any, output_paths: Any = None, parallel: Any = True, callback: Any = None) -> Any: ...
    def reproject_lidars(self, inputs: Any, dst_epsg: Any, output_paths: Any = None, parallel: Any = True, callback: Any = None) -> Any: ...

    def write_raster(self, raster: Any, output_path: Any, compress: Any = False, remove_after_write: Any = False) -> Any: ...
    def remove_raster_from_memory(self, raster: Any) -> Any: ...
    def clear_raster_memory(self) -> Any: ...
    def raster_memory_count(self) -> Any: ...
    def raster_memory_bytes(self) -> Any: ...
    def write_vector(self, vector: Any, output_path: Any) -> Any: ...
    def write_lidar(self, lidar: Any, output_path: Any) -> Any: ...
    def write_text(self, text: Any, file_name: Any) -> Any: ...

class WbToolCategory:
    def __dir__(self) -> list[str]: ...
    def __getattr__(self, name: Any) -> WbCategoryToolCallable: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def list_tools(self, include_pro_markers: Any = True) -> list[str]: ...

class WbCategoryToolCallable:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __dir__(self) -> Any: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class WbDomainNamespace:
    def __dir__(self) -> list[str]: ...
    def __getattr__(self, name: Any) -> WbCategoryToolCallable: ...
    def __ge__(self, value: Any) -> Any: ...
    def __gt__(self, value: Any) -> Any: ...
    def __le__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def list_tools(self, include_pro_markers: Any = True) -> list[str]: ...


# BEGIN GENERATED CATEGORY/DOMAIN STUBS
class WbRasterToolsCategory(WbToolCategory):
    def abs(self, **kwargs: Any) -> Any: ...
    def accumulation_curvature(self, **kwargs: Any) -> Any: ...
    def adaptive_filter(self, **kwargs: Any) -> Any: ...
    def add(self, **kwargs: Any) -> Any: ...
    def aggregate_raster(self, **kwargs: Any) -> Any: ...
    def anisotropic_diffusion_filter(self, **kwargs: Any) -> Any: ...
    def anova(self, **kwargs: Any) -> Any: ...
    def arccos(self, **kwargs: Any) -> Any: ...
    def arcosh(self, **kwargs: Any) -> Any: ...
    def arcsin(self, **kwargs: Any) -> Any: ...
    def arctan(self, **kwargs: Any) -> Any: ...
    def arsinh(self, **kwargs: Any) -> Any: ...
    def artanh(self, **kwargs: Any) -> Any: ...
    def aspect(self, **kwargs: Any) -> Any: ...
    def atan2(self, **kwargs: Any) -> Any: ...
    def average_flowpath_slope(self, **kwargs: Any) -> Any: ...
    def average_normal_vector_angular_deviation(self, **kwargs: Any) -> Any: ...
    def average_overlay(self, **kwargs: Any) -> Any: ...
    def average_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def balance_contrast_enhancement(self, **kwargs: Any) -> Any: ...
    def basins(self, **kwargs: Any) -> Any: ...
    def bilateral_filter(self, **kwargs: Any) -> Any: ...
    def block_maximum(self, **kwargs: Any) -> Any: ...
    def block_minimum(self, **kwargs: Any) -> Any: ...
    def bool_and(self, **kwargs: Any) -> Any: ...
    def bool_not(self, **kwargs: Any) -> Any: ...
    def bool_or(self, **kwargs: Any) -> Any: ...
    def bool_xor(self, **kwargs: Any) -> Any: ...
    def boundary_shape_complexity(self, **kwargs: Any) -> Any: ...
    def breach_depressions_least_cost(self, **kwargs: Any) -> Any: ...
    def breach_single_cell_pits(self, **kwargs: Any) -> Any: ...
    def buffer_raster(self, **kwargs: Any) -> Any: ...
    def burn_streams(self, **kwargs: Any) -> Any: ...
    def canny_edge_detection(self, **kwargs: Any) -> Any: ...
    def casorati_curvature(self, **kwargs: Any) -> Any: ...
    def ceil(self, **kwargs: Any) -> Any: ...
    def centroid_raster(self, **kwargs: Any) -> Any: ...
    def change_vector_analysis(self, **kwargs: Any) -> Any: ...
    def circular_variance_of_aspect(self, **kwargs: Any) -> Any: ...
    def clip_raster_to_polygon(self, **kwargs: Any) -> Any: ...
    def closing(self, **kwargs: Any) -> Any: ...
    def clump(self, **kwargs: Any) -> Any: ...
    def conditional_evaluation(self, **kwargs: Any) -> Any: ...
    def conservative_smoothing_filter(self, **kwargs: Any) -> Any: ...
    def convergence_index(self, **kwargs: Any) -> Any: ...
    def corner_detection(self, **kwargs: Any) -> Any: ...
    def correct_vignetting(self, **kwargs: Any) -> Any: ...
    def cos(self, **kwargs: Any) -> Any: ...
    def cosh(self, **kwargs: Any) -> Any: ...
    def cost_allocation(self, **kwargs: Any) -> Any: ...
    def cost_distance(self, **kwargs: Any) -> Any: ...
    def cost_pathway(self, **kwargs: Any) -> Any: ...
    def count_if(self, **kwargs: Any) -> Any: ...
    def create_colour_composite(self, **kwargs: Any) -> Any: ...
    def create_plane(self, **kwargs: Any) -> Any: ...
    def crispness_index(self, **kwargs: Any) -> Any: ...
    def cross_tabulation(self, **kwargs: Any) -> Any: ...
    def cumulative_distribution(self, **kwargs: Any) -> Any: ...
    def curvedness(self, **kwargs: Any) -> Any: ...
    def d8_flow_accum(self, **kwargs: Any) -> Any: ...
    def d8_mass_flux(self, **kwargs: Any) -> Any: ...
    def d8_pointer(self, **kwargs: Any) -> Any: ...
    def dbscan(self, **kwargs: Any) -> Any: ...
    def decrement(self, **kwargs: Any) -> Any: ...
    def deviation_from_mean_elevation(self, **kwargs: Any) -> Any: ...
    def diff_of_gaussians_filter(self, **kwargs: Any) -> Any: ...
    def difference_curvature(self, **kwargs: Any) -> Any: ...
    def difference_from_mean_elevation(self, **kwargs: Any) -> Any: ...
    def dinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def dinf_mass_flux(self, **kwargs: Any) -> Any: ...
    def dinf_pointer(self, **kwargs: Any) -> Any: ...
    def direct_decorrelation_stretch(self, **kwargs: Any) -> Any: ...
    def directional_relief(self, **kwargs: Any) -> Any: ...
    def distance_to_outlet(self, **kwargs: Any) -> Any: ...
    def diversity_filter(self, **kwargs: Any) -> Any: ...
    def divide(self, **kwargs: Any) -> Any: ...
    def downslope_distance_to_stream(self, **kwargs: Any) -> Any: ...
    def downslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def downslope_index(self, **kwargs: Any) -> Any: ...
    def edge_contamination(self, **kwargs: Any) -> Any: ...
    def edge_density(self, **kwargs: Any) -> Any: ...
    def edge_preserving_mean_filter(self, **kwargs: Any) -> Any: ...
    def edge_proportion(self, **kwargs: Any) -> Any: ...
    def elev_above_pit(self, **kwargs: Any) -> Any: ...
    def elev_above_pit_dist(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_min_max(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_watershed_min_max(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream_euclidean(self, **kwargs: Any) -> Any: ...
    def elevation_percentile(self, **kwargs: Any) -> Any: ...
    def embankment_mapping(self, **kwargs: Any) -> Any: ...
    def emboss_filter(self, **kwargs: Any) -> Any: ...
    def equal_to(self, **kwargs: Any) -> Any: ...
    def erase_polygon_from_raster(self, **kwargs: Any) -> Any: ...
    def euclidean_allocation(self, **kwargs: Any) -> Any: ...
    def euclidean_distance(self, **kwargs: Any) -> Any: ...
    def evaluate_training_sites(self, **kwargs: Any) -> Any: ...
    def exp(self, **kwargs: Any) -> Any: ...
    def exp2(self, **kwargs: Any) -> Any: ...
    def exposure_towards_wind_flux(self, **kwargs: Any) -> Any: ...
    def extract_streams(self, **kwargs: Any) -> Any: ...
    def extract_valleys(self, **kwargs: Any) -> Any: ...
    def farthest_channel_head(self, **kwargs: Any) -> Any: ...
    def fast_almost_gaussian_filter(self, **kwargs: Any) -> Any: ...
    def fd8_flow_accum(self, **kwargs: Any) -> Any: ...
    def fd8_pointer(self, **kwargs: Any) -> Any: ...
    def feature_preserving_smoothing(self, **kwargs: Any) -> Any: ...
    def fetch_analysis(self, **kwargs: Any) -> Any: ...
    def fill_depressions(self, **kwargs: Any) -> Any: ...
    def fill_depressions_planchon_and_darboux(self, **kwargs: Any) -> Any: ...
    def fill_depressions_wang_and_liu(self, **kwargs: Any) -> Any: ...
    def fill_missing_data(self, **kwargs: Any) -> Any: ...
    def fill_pits(self, **kwargs: Any) -> Any: ...
    def filter_raster_features_by_area(self, **kwargs: Any) -> Any: ...
    def find_main_stem(self, **kwargs: Any) -> Any: ...
    def find_noflow_cells(self, **kwargs: Any) -> Any: ...
    def find_parallel_flow(self, **kwargs: Any) -> Any: ...
    def find_patch_edge_cells(self, **kwargs: Any) -> Any: ...
    def find_ridges(self, **kwargs: Any) -> Any: ...
    def flip_image(self, **kwargs: Any) -> Any: ...
    def floor(self, **kwargs: Any) -> Any: ...
    def flow_accum_full_workflow(self, **kwargs: Any) -> Any: ...
    def flow_length_diff(self, **kwargs: Any) -> Any: ...
    def frangi_filter(self, **kwargs: Any) -> Any: ...
    def frost_filter(self, **kwargs: Any) -> Any: ...
    def fuzzy_knn_classification(self, **kwargs: Any) -> Any: ...
    def gabor_filter_bank(self, **kwargs: Any) -> Any: ...
    def gamma_correction(self, **kwargs: Any) -> Any: ...
    def gamma_map_filter(self, **kwargs: Any) -> Any: ...
    def gaussian_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def gaussian_curvature(self, **kwargs: Any) -> Any: ...
    def gaussian_filter(self, **kwargs: Any) -> Any: ...
    def generalize_classified_raster(self, **kwargs: Any) -> Any: ...
    def generalize_with_similarity(self, **kwargs: Any) -> Any: ...
    def generating_function(self, **kwargs: Any) -> Any: ...
    def geomorphons(self, **kwargs: Any) -> Any: ...
    def greater_than(self, **kwargs: Any) -> Any: ...
    def guided_filter(self, **kwargs: Any) -> Any: ...
    def hack_stream_order(self, **kwargs: Any) -> Any: ...
    def heat_map(self, **kwargs: Any) -> Any: ...
    def high_pass_bilateral_filter(self, **kwargs: Any) -> Any: ...
    def high_pass_filter(self, **kwargs: Any) -> Any: ...
    def high_pass_median_filter(self, **kwargs: Any) -> Any: ...
    def highest_position(self, **kwargs: Any) -> Any: ...
    def hillshade(self, **kwargs: Any) -> Any: ...
    def histogram_equalization(self, **kwargs: Any) -> Any: ...
    def histogram_matching(self, **kwargs: Any) -> Any: ...
    def histogram_matching_two_images(self, **kwargs: Any) -> Any: ...
    def horizontal_excess_curvature(self, **kwargs: Any) -> Any: ...
    def horton_ratios(self, **kwargs: Any) -> Any: ...
    def horton_stream_order(self, **kwargs: Any) -> Any: ...
    def hypsometric_analysis(self, **kwargs: Any) -> Any: ...
    def idw_interpolation(self, **kwargs: Any) -> Any: ...
    def ihs_to_rgb(self, **kwargs: Any) -> Any: ...
    def image_autocorrelation(self, **kwargs: Any) -> Any: ...
    def image_correlation(self, **kwargs: Any) -> Any: ...
    def image_correlation_neighbourhood_analysis(self, **kwargs: Any) -> Any: ...
    def image_regression(self, **kwargs: Any) -> Any: ...
    def image_segmentation(self, **kwargs: Any) -> Any: ...
    def image_slider(self, **kwargs: Any) -> Any: ...
    def image_stack_profile(self, **kwargs: Any) -> Any: ...
    def increment(self, **kwargs: Any) -> Any: ...
    def inplace_add(self, **kwargs: Any) -> Any: ...
    def inplace_divide(self, **kwargs: Any) -> Any: ...
    def inplace_multiply(self, **kwargs: Any) -> Any: ...
    def inplace_subtract(self, **kwargs: Any) -> Any: ...
    def integer_division(self, **kwargs: Any) -> Any: ...
    def integral_image_transform(self, **kwargs: Any) -> Any: ...
    def inverse_pca(self, **kwargs: Any) -> Any: ...
    def is_nodata(self, **kwargs: Any) -> Any: ...
    def k_means_clustering(self, **kwargs: Any) -> Any: ...
    def k_nearest_mean_filter(self, **kwargs: Any) -> Any: ...
    def kappa_index(self, **kwargs: Any) -> Any: ...
    def knn_classification(self, **kwargs: Any) -> Any: ...
    def knn_regression(self, **kwargs: Any) -> Any: ...
    def ks_normality_test(self, **kwargs: Any) -> Any: ...
    def kuan_filter(self, **kwargs: Any) -> Any: ...
    def kuwahara_filter(self, **kwargs: Any) -> Any: ...
    def laplacian_filter(self, **kwargs: Any) -> Any: ...
    def laplacian_of_gaussians_filter(self, **kwargs: Any) -> Any: ...
    def lee_filter(self, **kwargs: Any) -> Any: ...
    def length_of_upstream_channels(self, **kwargs: Any) -> Any: ...
    def less_than(self, **kwargs: Any) -> Any: ...
    def line_detection_filter(self, **kwargs: Any) -> Any: ...
    def line_thinning(self, **kwargs: Any) -> Any: ...
    def list_unique_values_raster(self, **kwargs: Any) -> Any: ...
    def ln(self, **kwargs: Any) -> Any: ...
    def log10(self, **kwargs: Any) -> Any: ...
    def log2(self, **kwargs: Any) -> Any: ...
    def logistic_regression(self, **kwargs: Any) -> Any: ...
    def long_profile(self, **kwargs: Any) -> Any: ...
    def long_profile_from_points(self, **kwargs: Any) -> Any: ...
    def lowest_position(self, **kwargs: Any) -> Any: ...
    def majority_filter(self, **kwargs: Any) -> Any: ...
    def map_features(self, **kwargs: Any) -> Any: ...
    def map_off_terrain_objects(self, **kwargs: Any) -> Any: ...
    def max(self, **kwargs: Any) -> Any: ...
    def max_absolute_overlay(self, **kwargs: Any) -> Any: ...
    def max_anisotropy_dev(self, **kwargs: Any) -> Any: ...
    def max_branch_length(self, **kwargs: Any) -> Any: ...
    def max_difference_from_mean(self, **kwargs: Any) -> Any: ...
    def max_downslope_elev_change(self, **kwargs: Any) -> Any: ...
    def max_elevation_deviation(self, **kwargs: Any) -> Any: ...
    def max_overlay(self, **kwargs: Any) -> Any: ...
    def max_upslope_elev_change(self, **kwargs: Any) -> Any: ...
    def max_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def max_upslope_value(self, **kwargs: Any) -> Any: ...
    def maximal_curvature(self, **kwargs: Any) -> Any: ...
    def maximum_filter(self, **kwargs: Any) -> Any: ...
    def mdinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def mean_curvature(self, **kwargs: Any) -> Any: ...
    def mean_filter(self, **kwargs: Any) -> Any: ...
    def median_filter(self, **kwargs: Any) -> Any: ...
    def min(self, **kwargs: Any) -> Any: ...
    def min_absolute_overlay(self, **kwargs: Any) -> Any: ...
    def min_dist_classification(self, **kwargs: Any) -> Any: ...
    def min_downslope_elev_change(self, **kwargs: Any) -> Any: ...
    def min_max_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def min_overlay(self, **kwargs: Any) -> Any: ...
    def minimal_curvature(self, **kwargs: Any) -> Any: ...
    def minimal_dispersion_flow_algorithm(self, **kwargs: Any) -> Any: ...
    def minimum_filter(self, **kwargs: Any) -> Any: ...
    def modified_k_means_clustering(self, **kwargs: Any) -> Any: ...
    def modified_shepard_interpolation(self, **kwargs: Any) -> Any: ...
    def modulo(self, **kwargs: Any) -> Any: ...
    def mosaic(self, **kwargs: Any) -> Any: ...
    def mosaic_with_feathering(self, **kwargs: Any) -> Any: ...
    def multidirectional_hillshade(self, **kwargs: Any) -> Any: ...
    def multiply(self, **kwargs: Any) -> Any: ...
    def multiply_overlay(self, **kwargs: Any) -> Any: ...
    def multiscale_elevated_index(self, **kwargs: Any) -> Any: ...
    def multiscale_elevation_percentile(self, **kwargs: Any) -> Any: ...
    def multiscale_low_lying_index(self, **kwargs: Any) -> Any: ...
    def multiscale_roughness(self, **kwargs: Any) -> Any: ...
    def multiscale_std_dev_normals(self, **kwargs: Any) -> Any: ...
    def multiscale_topographic_position_image(self, **kwargs: Any) -> Any: ...
    def natural_neighbour_interpolation(self, **kwargs: Any) -> Any: ...
    def nearest_neighbour_interpolation(self, **kwargs: Any) -> Any: ...
    def negate(self, **kwargs: Any) -> Any: ...
    def nibble(self, **kwargs: Any) -> Any: ...
    def nnd_classification(self, **kwargs: Any) -> Any: ...
    def non_local_means_filter(self, **kwargs: Any) -> Any: ...
    def normalized_difference_index(self, **kwargs: Any) -> Any: ...
    def not_equal_to(self, **kwargs: Any) -> Any: ...
    def num_downslope_neighbours(self, **kwargs: Any) -> Any: ...
    def num_inflowing_neighbours(self, **kwargs: Any) -> Any: ...
    def num_upslope_neighbours(self, **kwargs: Any) -> Any: ...
    def olympic_filter(self, **kwargs: Any) -> Any: ...
    def opening(self, **kwargs: Any) -> Any: ...
    def openness(self, **kwargs: Any) -> Any: ...
    def otsu_thresholding(self, **kwargs: Any) -> Any: ...
    def paired_sample_t_test(self, **kwargs: Any) -> Any: ...
    def panchromatic_sharpening(self, **kwargs: Any) -> Any: ...
    def parallelepiped_classification(self, **kwargs: Any) -> Any: ...
    def pennock_landform_classification(self, **kwargs: Any) -> Any: ...
    def percent_elev_range(self, **kwargs: Any) -> Any: ...
    def percent_equal_to(self, **kwargs: Any) -> Any: ...
    def percent_greater_than(self, **kwargs: Any) -> Any: ...
    def percent_less_than(self, **kwargs: Any) -> Any: ...
    def percentage_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def percentile_filter(self, **kwargs: Any) -> Any: ...
    def phi_coefficient(self, **kwargs: Any) -> Any: ...
    def pick_from_list(self, **kwargs: Any) -> Any: ...
    def piecewise_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def plan_curvature(self, **kwargs: Any) -> Any: ...
    def power(self, **kwargs: Any) -> Any: ...
    def prewitt_filter(self, **kwargs: Any) -> Any: ...
    def principal_component_analysis(self, **kwargs: Any) -> Any: ...
    def principal_curvature_direction(self, **kwargs: Any) -> Any: ...
    def profile(self, **kwargs: Any) -> Any: ...
    def profile_curvature(self, **kwargs: Any) -> Any: ...
    def qin_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def quantiles(self, **kwargs: Any) -> Any: ...
    def quinn_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def radial_basis_function_interpolation(self, **kwargs: Any) -> Any: ...
    def radius_of_gyration(self, **kwargs: Any) -> Any: ...
    def random_field(self, **kwargs: Any) -> Any: ...
    def random_forest_classification(self, **kwargs: Any) -> Any: ...
    def random_forest_classification_fit(self, **kwargs: Any) -> Any: ...
    def random_forest_classification_predict(self, **kwargs: Any) -> Any: ...
    def random_forest_regression(self, **kwargs: Any) -> Any: ...
    def random_forest_regression_fit(self, **kwargs: Any) -> Any: ...
    def random_forest_regression_predict(self, **kwargs: Any) -> Any: ...
    def random_sample(self, **kwargs: Any) -> Any: ...
    def range_filter(self, **kwargs: Any) -> Any: ...
    def raster_area(self, **kwargs: Any) -> Any: ...
    def raster_calculator(self, **kwargs: Any) -> Any: ...
    def raster_cell_assignment(self, **kwargs: Any) -> Any: ...
    def raster_histogram(self, **kwargs: Any) -> Any: ...
    def raster_perimeter(self, **kwargs: Any) -> Any: ...
    def raster_streams_to_vector(self, **kwargs: Any) -> Any: ...
    def raster_summary_stats(self, **kwargs: Any) -> Any: ...
    def rasterize_streams(self, **kwargs: Any) -> Any: ...
    def reciprocal(self, **kwargs: Any) -> Any: ...
    def reclass(self, **kwargs: Any) -> Any: ...
    def reclass_equal_interval(self, **kwargs: Any) -> Any: ...
    def relative_aspect(self, **kwargs: Any) -> Any: ...
    def relative_stream_power_index(self, **kwargs: Any) -> Any: ...
    def relative_topographic_position(self, **kwargs: Any) -> Any: ...
    def remove_off_terrain_objects(self, **kwargs: Any) -> Any: ...
    def remove_short_streams(self, **kwargs: Any) -> Any: ...
    def remove_spurs(self, **kwargs: Any) -> Any: ...
    def repair_stream_vector_topology(self, **kwargs: Any) -> Any: ...
    def resample(self, **kwargs: Any) -> Any: ...
    def rescale_value_range(self, **kwargs: Any) -> Any: ...
    def rgb_to_ihs(self, **kwargs: Any) -> Any: ...
    def rho8_flow_accum(self, **kwargs: Any) -> Any: ...
    def rho8_pointer(self, **kwargs: Any) -> Any: ...
    def ring_curvature(self, **kwargs: Any) -> Any: ...
    def roberts_cross_filter(self, **kwargs: Any) -> Any: ...
    def root_mean_square_error(self, **kwargs: Any) -> Any: ...
    def rotor(self, **kwargs: Any) -> Any: ...
    def round(self, **kwargs: Any) -> Any: ...
    def ruggedness_index(self, **kwargs: Any) -> Any: ...
    def savitzky_golay_2d_filter(self, **kwargs: Any) -> Any: ...
    def scharr_filter(self, **kwargs: Any) -> Any: ...
    def sediment_transport_index(self, **kwargs: Any) -> Any: ...
    def shape_complexity_index_raster(self, **kwargs: Any) -> Any: ...
    def shape_index(self, **kwargs: Any) -> Any: ...
    def shreve_stream_magnitude(self, **kwargs: Any) -> Any: ...
    def sieve(self, **kwargs: Any) -> Any: ...
    def sigmoidal_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def sin(self, **kwargs: Any) -> Any: ...
    def sinh(self, **kwargs: Any) -> Any: ...
    def slope(self, **kwargs: Any) -> Any: ...
    def slope_vs_elev_plot(self, **kwargs: Any) -> Any: ...
    def sobel_filter(self, **kwargs: Any) -> Any: ...
    def spherical_std_dev_of_normals(self, **kwargs: Any) -> Any: ...
    def split_colour_composite(self, **kwargs: Any) -> Any: ...
    def sqrt(self, **kwargs: Any) -> Any: ...
    def square(self, **kwargs: Any) -> Any: ...
    def standard_deviation_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def standard_deviation_filter(self, **kwargs: Any) -> Any: ...
    def standard_deviation_of_slope(self, **kwargs: Any) -> Any: ...
    def standard_deviation_overlay(self, **kwargs: Any) -> Any: ...
    def strahler_stream_order(self, **kwargs: Any) -> Any: ...
    def stream_link_class(self, **kwargs: Any) -> Any: ...
    def stream_link_identifier(self, **kwargs: Any) -> Any: ...
    def stream_link_length(self, **kwargs: Any) -> Any: ...
    def stream_link_slope(self, **kwargs: Any) -> Any: ...
    def stream_slope_continuous(self, **kwargs: Any) -> Any: ...
    def subtract(self, **kwargs: Any) -> Any: ...
    def sum_overlay(self, **kwargs: Any) -> Any: ...
    def surface_area_ratio(self, **kwargs: Any) -> Any: ...
    def svm_classification(self, **kwargs: Any) -> Any: ...
    def svm_regression(self, **kwargs: Any) -> Any: ...
    def tan(self, **kwargs: Any) -> Any: ...
    def tangential_curvature(self, **kwargs: Any) -> Any: ...
    def tanh(self, **kwargs: Any) -> Any: ...
    def thicken_raster_line(self, **kwargs: Any) -> Any: ...
    def tin_interpolation(self, **kwargs: Any) -> Any: ...
    def to_degrees(self, **kwargs: Any) -> Any: ...
    def to_radians(self, **kwargs: Any) -> Any: ...
    def tophat_transform(self, **kwargs: Any) -> Any: ...
    def topological_stream_order(self, **kwargs: Any) -> Any: ...
    def total_curvature(self, **kwargs: Any) -> Any: ...
    def total_filter(self, **kwargs: Any) -> Any: ...
    def trend_surface(self, **kwargs: Any) -> Any: ...
    def trend_surface_vector_points(self, **kwargs: Any) -> Any: ...
    def tributary_identifier(self, **kwargs: Any) -> Any: ...
    def truncate(self, **kwargs: Any) -> Any: ...
    def turning_bands_simulation(self, **kwargs: Any) -> Any: ...
    def two_sample_ks_test(self, **kwargs: Any) -> Any: ...
    def unsharp_masking(self, **kwargs: Any) -> Any: ...
    def unsphericity(self, **kwargs: Any) -> Any: ...
    def update_nodata_cells(self, **kwargs: Any) -> Any: ...
    def user_defined_weights_filter(self, **kwargs: Any) -> Any: ...
    def vector_stream_network_analysis(self, **kwargs: Any) -> Any: ...
    def vertical_excess_curvature(self, **kwargs: Any) -> Any: ...
    def viewshed(self, **kwargs: Any) -> Any: ...
    def weighted_overlay(self, **kwargs: Any) -> Any: ...
    def weighted_sum(self, **kwargs: Any) -> Any: ...
    def wetness_index(self, **kwargs: Any) -> Any: ...
    def wiener_filter(self, **kwargs: Any) -> Any: ...
    def wilcoxon_signed_rank_test(self, **kwargs: Any) -> Any: ...
    def write_function_memory_insertion(self, **kwargs: Any) -> Any: ...
    def z_scores(self, **kwargs: Any) -> Any: ...
    def zonal_statistics(self, **kwargs: Any) -> Any: ...

class WbVectorToolsCategory(WbToolCategory):
    def attribute_correlation(self, **kwargs: Any) -> Any: ...
    def attribute_histogram(self, **kwargs: Any) -> Any: ...
    def attribute_scattergram(self, **kwargs: Any) -> Any: ...
    def buffer_vector(self, **kwargs: Any) -> Any: ...
    def centroid_vector(self, **kwargs: Any) -> Any: ...
    def clip(self, **kwargs: Any) -> Any: ...
    def compactness_ratio(self, **kwargs: Any) -> Any: ...
    def construct_vector_tin(self, **kwargs: Any) -> Any: ...
    def contours_from_points(self, **kwargs: Any) -> Any: ...
    def contours_from_raster(self, **kwargs: Any) -> Any: ...
    def deviation_from_regional_direction(self, **kwargs: Any) -> Any: ...
    def difference(self, **kwargs: Any) -> Any: ...
    def dissolve(self, **kwargs: Any) -> Any: ...
    def eliminate_coincident_points(self, **kwargs: Any) -> Any: ...
    def elongation_ratio(self, **kwargs: Any) -> Any: ...
    def erase(self, **kwargs: Any) -> Any: ...
    def extend_vector_lines(self, **kwargs: Any) -> Any: ...
    def extract_by_attribute(self, **kwargs: Any) -> Any: ...
    def extract_nodes(self, **kwargs: Any) -> Any: ...
    def extract_raster_values_at_points(self, **kwargs: Any) -> Any: ...
    def filter_vector_features_by_area(self, **kwargs: Any) -> Any: ...
    def find_lowest_or_highest_points(self, **kwargs: Any) -> Any: ...
    def hexagonal_grid_from_raster_base(self, **kwargs: Any) -> Any: ...
    def hexagonal_grid_from_vector_base(self, **kwargs: Any) -> Any: ...
    def hole_proportion(self, **kwargs: Any) -> Any: ...
    def intersect(self, **kwargs: Any) -> Any: ...
    def layer_footprint_raster(self, **kwargs: Any) -> Any: ...
    def layer_footprint_vector(self, **kwargs: Any) -> Any: ...
    def line_intersections(self, **kwargs: Any) -> Any: ...
    def linearity_index(self, **kwargs: Any) -> Any: ...
    def list_unique_values(self, **kwargs: Any) -> Any: ...
    def medoid(self, **kwargs: Any) -> Any: ...
    def merge_line_segments(self, **kwargs: Any) -> Any: ...
    def minimum_bounding_box(self, **kwargs: Any) -> Any: ...
    def minimum_bounding_circle(self, **kwargs: Any) -> Any: ...
    def minimum_bounding_envelope(self, **kwargs: Any) -> Any: ...
    def minimum_convex_hull(self, **kwargs: Any) -> Any: ...
    def narrowness_index(self, **kwargs: Any) -> Any: ...
    def patch_orientation(self, **kwargs: Any) -> Any: ...
    def perimeter_area_ratio(self, **kwargs: Any) -> Any: ...
    def polygon_area(self, **kwargs: Any) -> Any: ...
    def polygon_long_axis(self, **kwargs: Any) -> Any: ...
    def polygon_perimeter(self, **kwargs: Any) -> Any: ...
    def polygon_short_axis(self, **kwargs: Any) -> Any: ...
    def polygonize(self, **kwargs: Any) -> Any: ...
    def rectangular_grid_from_raster_base(self, **kwargs: Any) -> Any: ...
    def rectangular_grid_from_vector_base(self, **kwargs: Any) -> Any: ...
    def related_circumscribing_circle(self, **kwargs: Any) -> Any: ...
    def shape_complexity_index_vector(self, **kwargs: Any) -> Any: ...
    def smooth_vectors(self, **kwargs: Any) -> Any: ...
    def snap_endnodes(self, **kwargs: Any) -> Any: ...
    def split_vector_lines(self, **kwargs: Any) -> Any: ...
    def split_with_lines(self, **kwargs: Any) -> Any: ...
    def symmetrical_difference(self, **kwargs: Any) -> Any: ...
    def travelling_salesman_problem(self, **kwargs: Any) -> Any: ...
    def union(self, **kwargs: Any) -> Any: ...
    def vector_hex_binning(self, **kwargs: Any) -> Any: ...
    def voronoi_diagram(self, **kwargs: Any) -> Any: ...

class WbLidarToolsCategory(WbToolCategory):
    def ascii_to_las(self, **kwargs: Any) -> Any: ...
    def classify_buildings_in_lidar(self, **kwargs: Any) -> Any: ...
    def classify_lidar(self, **kwargs: Any) -> Any: ...
    def classify_overlap_points(self, **kwargs: Any) -> Any: ...
    def clip_lidar_to_polygon(self, **kwargs: Any) -> Any: ...
    def colourize_based_on_class(self, **kwargs: Any) -> Any: ...
    def colourize_based_on_point_returns(self, **kwargs: Any) -> Any: ...
    def erase_polygon_from_lidar(self, **kwargs: Any) -> Any: ...
    def filter_lidar(self, **kwargs: Any) -> Any: ...
    def filter_lidar_by_percentile(self, **kwargs: Any) -> Any: ...
    def filter_lidar_by_reference_surface(self, **kwargs: Any) -> Any: ...
    def filter_lidar_classes(self, **kwargs: Any) -> Any: ...
    def filter_lidar_noise(self, **kwargs: Any) -> Any: ...
    def filter_lidar_scan_angles(self, **kwargs: Any) -> Any: ...
    def find_flightline_edge_points(self, **kwargs: Any) -> Any: ...
    def flightline_overlap(self, **kwargs: Any) -> Any: ...
    def height_above_ground(self, **kwargs: Any) -> Any: ...
    def individual_tree_detection(self, **kwargs: Any) -> Any: ...
    def individual_tree_segmentation(self, **kwargs: Any) -> Any: ...
    def las_to_ascii(self, **kwargs: Any) -> Any: ...
    def las_to_shapefile(self, **kwargs: Any) -> Any: ...
    def lidar_block_maximum(self, **kwargs: Any) -> Any: ...
    def lidar_block_minimum(self, **kwargs: Any) -> Any: ...
    def lidar_classify_subset(self, **kwargs: Any) -> Any: ...
    def lidar_colourize(self, **kwargs: Any) -> Any: ...
    def lidar_construct_vector_tin(self, **kwargs: Any) -> Any: ...
    def lidar_contour(self, **kwargs: Any) -> Any: ...
    def lidar_digital_surface_model(self, **kwargs: Any) -> Any: ...
    def lidar_eigenvalue_features(self, **kwargs: Any) -> Any: ...
    def lidar_elevation_slice(self, **kwargs: Any) -> Any: ...
    def lidar_ground_point_filter(self, **kwargs: Any) -> Any: ...
    def lidar_hex_bin(self, **kwargs: Any) -> Any: ...
    def lidar_hillshade(self, **kwargs: Any) -> Any: ...
    def lidar_histogram(self, **kwargs: Any) -> Any: ...
    def lidar_idw_interpolation(self, **kwargs: Any) -> Any: ...
    def lidar_info(self, **kwargs: Any) -> Any: ...
    def lidar_join(self, **kwargs: Any) -> Any: ...
    def lidar_kappa(self, **kwargs: Any) -> Any: ...
    def lidar_nearest_neighbour_gridding(self, **kwargs: Any) -> Any: ...
    def lidar_point_density(self, **kwargs: Any) -> Any: ...
    def lidar_point_return_analysis(self, **kwargs: Any) -> Any: ...
    def lidar_point_stats(self, **kwargs: Any) -> Any: ...
    def lidar_radial_basis_function_interpolation(self, **kwargs: Any) -> Any: ...
    def lidar_ransac_planes(self, **kwargs: Any) -> Any: ...
    def lidar_remove_outliers(self, **kwargs: Any) -> Any: ...
    def lidar_rooftop_analysis(self, **kwargs: Any) -> Any: ...
    def lidar_segmentation(self, **kwargs: Any) -> Any: ...
    def lidar_segmentation_based_filter(self, **kwargs: Any) -> Any: ...
    def lidar_shift(self, **kwargs: Any) -> Any: ...
    def lidar_sibson_interpolation(self, **kwargs: Any) -> Any: ...
    def lidar_thin(self, **kwargs: Any) -> Any: ...
    def lidar_thin_high_density(self, **kwargs: Any) -> Any: ...
    def lidar_tile(self, **kwargs: Any) -> Any: ...
    def lidar_tile_footprint(self, **kwargs: Any) -> Any: ...
    def lidar_tin_gridding(self, **kwargs: Any) -> Any: ...
    def lidar_tophat_transform(self, **kwargs: Any) -> Any: ...
    def modify_lidar(self, **kwargs: Any) -> Any: ...
    def normal_vectors(self, **kwargs: Any) -> Any: ...
    def normalize_lidar(self, **kwargs: Any) -> Any: ...
    def recover_flightline_info(self, **kwargs: Any) -> Any: ...
    def remove_duplicates(self, **kwargs: Any) -> Any: ...
    def select_tiles_by_polygon(self, **kwargs: Any) -> Any: ...
    def sort_lidar(self, **kwargs: Any) -> Any: ...
    def split_lidar(self, **kwargs: Any) -> Any: ...

class WbTopologyCategory(WbToolCategory):
    ...

class WbHydrologyCategory(WbToolCategory):
    def average_flowpath_slope(self, **kwargs: Any) -> Any: ...
    def average_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def basins(self, **kwargs: Any) -> Any: ...
    def breach_depressions_least_cost(self, **kwargs: Any) -> Any: ...
    def breach_single_cell_pits(self, **kwargs: Any) -> Any: ...
    def burn_streams_at_roads(self, **kwargs: Any) -> Any: ...
    def d8_flow_accum(self, **kwargs: Any) -> Any: ...
    def d8_mass_flux(self, **kwargs: Any) -> Any: ...
    def d8_pointer(self, **kwargs: Any) -> Any: ...
    def depth_in_sink(self, **kwargs: Any) -> Any: ...
    def depth_to_water(self, **kwargs: Any) -> Any: ...
    def dinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def dinf_mass_flux(self, **kwargs: Any) -> Any: ...
    def dinf_pointer(self, **kwargs: Any) -> Any: ...
    def downslope_distance_to_stream(self, **kwargs: Any) -> Any: ...
    def downslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def downslope_index(self, **kwargs: Any) -> Any: ...
    def edge_contamination(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_watershed_min_max(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream_euclidean(self, **kwargs: Any) -> Any: ...
    def fd8_flow_accum(self, **kwargs: Any) -> Any: ...
    def fd8_pointer(self, **kwargs: Any) -> Any: ...
    def fill_burn(self, **kwargs: Any) -> Any: ...
    def fill_depressions(self, **kwargs: Any) -> Any: ...
    def fill_depressions_planchon_and_darboux(self, **kwargs: Any) -> Any: ...
    def fill_depressions_wang_and_liu(self, **kwargs: Any) -> Any: ...
    def fill_pits(self, **kwargs: Any) -> Any: ...
    def find_noflow_cells(self, **kwargs: Any) -> Any: ...
    def find_parallel_flow(self, **kwargs: Any) -> Any: ...
    def flatten_lakes(self, **kwargs: Any) -> Any: ...
    def flood_order(self, **kwargs: Any) -> Any: ...
    def flow_accum_full_workflow(self, **kwargs: Any) -> Any: ...
    def flow_length_diff(self, **kwargs: Any) -> Any: ...
    def hillslopes(self, **kwargs: Any) -> Any: ...
    def hydrologic_connectivity(self, **kwargs: Any) -> Any: ...
    def impoundment_size_index(self, **kwargs: Any) -> Any: ...
    def insert_dams(self, **kwargs: Any) -> Any: ...
    def isobasins(self, **kwargs: Any) -> Any: ...
    def jenson_snap_pour_points(self, **kwargs: Any) -> Any: ...
    def longest_flowpath(self, **kwargs: Any) -> Any: ...
    def max_branch_length(self, **kwargs: Any) -> Any: ...
    def max_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def max_upslope_value(self, **kwargs: Any) -> Any: ...
    def mdinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def minimal_dispersion_flow_algorithm(self, **kwargs: Any) -> Any: ...
    def num_inflowing_neighbours(self, **kwargs: Any) -> Any: ...
    def qin_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def quinn_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def raise_walls(self, **kwargs: Any) -> Any: ...
    def relative_stream_power_index(self, **kwargs: Any) -> Any: ...
    def rho8_flow_accum(self, **kwargs: Any) -> Any: ...
    def rho8_pointer(self, **kwargs: Any) -> Any: ...
    def sediment_transport_index(self, **kwargs: Any) -> Any: ...
    def sink(self, **kwargs: Any) -> Any: ...
    def snap_pour_points(self, **kwargs: Any) -> Any: ...
    def stochastic_depression_analysis(self, **kwargs: Any) -> Any: ...
    def strahler_order_basins(self, **kwargs: Any) -> Any: ...
    def strahler_stream_order(self, **kwargs: Any) -> Any: ...
    def subbasins(self, **kwargs: Any) -> Any: ...
    def trace_downslope_flowpaths(self, **kwargs: Any) -> Any: ...
    def unnest_basins(self, **kwargs: Any) -> Any: ...
    def upslope_depression_storage(self, **kwargs: Any) -> Any: ...
    def watershed(self, **kwargs: Any) -> Any: ...
    def watershed_from_raster_pour_points(self, **kwargs: Any) -> Any: ...
    def wetness_index(self, **kwargs: Any) -> Any: ...

class WbTerrainCategory(WbToolCategory):
    def average_flowpath_slope(self, **kwargs: Any) -> Any: ...
    def average_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def basins(self, **kwargs: Any) -> Any: ...
    def breach_depressions_least_cost(self, **kwargs: Any) -> Any: ...
    def breach_single_cell_pits(self, **kwargs: Any) -> Any: ...
    def horizon_angle(self, **kwargs: Any) -> Any: ...
    def d8_flow_accum(self, **kwargs: Any) -> Any: ...
    def d8_mass_flux(self, **kwargs: Any) -> Any: ...
    def d8_pointer(self, **kwargs: Any) -> Any: ...
    def hypsometrically_tinted_hillshade(self, **kwargs: Any) -> Any: ...
    def sky_view_factor(self, **kwargs: Any) -> Any: ...
    def dinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def dinf_mass_flux(self, **kwargs: Any) -> Any: ...
    def dinf_pointer(self, **kwargs: Any) -> Any: ...
    def downslope_distance_to_stream(self, **kwargs: Any) -> Any: ...
    def downslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def downslope_index(self, **kwargs: Any) -> Any: ...
    def edge_contamination(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_watershed_min_max(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream(self, **kwargs: Any) -> Any: ...
    def elevation_above_stream_euclidean(self, **kwargs: Any) -> Any: ...
    def fd8_flow_accum(self, **kwargs: Any) -> Any: ...
    def fd8_pointer(self, **kwargs: Any) -> Any: ...
    def time_in_daylight(self, **kwargs: Any) -> Any: ...
    def fill_depressions(self, **kwargs: Any) -> Any: ...
    def fill_depressions_planchon_and_darboux(self, **kwargs: Any) -> Any: ...
    def fill_depressions_wang_and_liu(self, **kwargs: Any) -> Any: ...
    def fill_pits(self, **kwargs: Any) -> Any: ...
    def find_noflow_cells(self, **kwargs: Any) -> Any: ...
    def find_parallel_flow(self, **kwargs: Any) -> Any: ...
    def visibility_index(self, **kwargs: Any) -> Any: ...

    def flow_accum_full_workflow(self, **kwargs: Any) -> Any: ...
    def flow_length_diff(self, **kwargs: Any) -> Any: ...
class WbConversionCategory(WbToolCategory):
    def add_point_coordinates_to_table(self, **kwargs: Any) -> Any: ...
    def clean_vector(self, **kwargs: Any) -> Any: ...
    def convert_nodata_to_zero(self, **kwargs: Any) -> Any: ...
    def csv_points_to_vector(self, **kwargs: Any) -> Any: ...
    def export_table_to_csv(self, **kwargs: Any) -> Any: ...
    def fix_dangling_arcs(self, **kwargs: Any) -> Any: ...
    def max_branch_length(self, **kwargs: Any) -> Any: ...
    def max_upslope_flowpath_length(self, **kwargs: Any) -> Any: ...
    def max_upslope_value(self, **kwargs: Any) -> Any: ...
    def mdinf_flow_accum(self, **kwargs: Any) -> Any: ...
    def minimal_dispersion_flow_algorithm(self, **kwargs: Any) -> Any: ...
    def num_inflowing_neighbours(self, **kwargs: Any) -> Any: ...
    def qin_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def quinn_flow_accumulation(self, **kwargs: Any) -> Any: ...
    def join_tables(self, **kwargs: Any) -> Any: ...
    def relative_stream_power_index(self, **kwargs: Any) -> Any: ...
    def rho8_flow_accum(self, **kwargs: Any) -> Any: ...
    def rho8_pointer(self, **kwargs: Any) -> Any: ...
    def sediment_transport_index(self, **kwargs: Any) -> Any: ...
    def lines_to_polygons(self, **kwargs: Any) -> Any: ...
    def merge_table_with_csv(self, **kwargs: Any) -> Any: ...
    def merge_vectors(self, **kwargs: Any) -> Any: ...
    def modify_nodata_value(self, **kwargs: Any) -> Any: ...
    def strahler_stream_order(self, **kwargs: Any) -> Any: ...
    def multipart_to_singlepart(self, **kwargs: Any) -> Any: ...
    def new_raster_from_base_raster(self, **kwargs: Any) -> Any: ...
    def new_raster_from_base_vector(self, **kwargs: Any) -> Any: ...
    def polygons_to_lines(self, **kwargs: Any) -> Any: ...
    def print_geotiff_tags(self, **kwargs: Any) -> Any: ...
    def raster_to_vector_lines(self, **kwargs: Any) -> Any: ...
    def wetness_index(self, **kwargs: Any) -> Any: ...
    def raster_to_vector_points(self, **kwargs: Any) -> Any: ...
    def raster_to_vector_polygons(self, **kwargs: Any) -> Any: ...
    def reinitialize_attribute_table(self, **kwargs: Any) -> Any: ...
    def remove_polygon_holes(self, **kwargs: Any) -> Any: ...
    def remove_raster_polygon_holes(self, **kwargs: Any) -> Any: ...
    def set_nodata_value(self, **kwargs: Any) -> Any: ...
    def singlepart_to_multipart(self, **kwargs: Any) -> Any: ...
    def vector_lines_to_raster(self, **kwargs: Any) -> Any: ...
    def vector_points_to_raster(self, **kwargs: Any) -> Any: ...
    def vector_polygons_to_raster(self, **kwargs: Any) -> Any: ...

class WbOtherCategory(WbToolCategory):
    def max_anisotropy_dev_signature(self, **kwargs: Any) -> Any: ...
    def max_elev_dev_signature(self, **kwargs: Any) -> Any: ...
    def multiscale_roughness_signature(self, **kwargs: Any) -> Any: ...
    def multiscale_std_dev_normals_signature(self, **kwargs: Any) -> Any: ...

class WbRemoteSensingDomain(WbDomainNamespace):
    def adaptive_filter(self, **kwargs: Any) -> Any: ...
    def anisotropic_diffusion_filter(self, **kwargs: Any) -> Any: ...
    def balance_contrast_enhancement(self, **kwargs: Any) -> Any: ...
    def canny_edge_detection(self, **kwargs: Any) -> Any: ...
    def change_vector_analysis(self, **kwargs: Any) -> Any: ...
    def closing(self, **kwargs: Any) -> Any: ...
    def conservative_smoothing_filter(self, **kwargs: Any) -> Any: ...
    def corner_detection(self, **kwargs: Any) -> Any: ...
    def correct_vignetting(self, **kwargs: Any) -> Any: ...
    def create_colour_composite(self, **kwargs: Any) -> Any: ...
    def diff_of_gaussians_filter(self, **kwargs: Any) -> Any: ...
    def direct_decorrelation_stretch(self, **kwargs: Any) -> Any: ...
    def diversity_filter(self, **kwargs: Any) -> Any: ...
    def edge_preserving_mean_filter(self, **kwargs: Any) -> Any: ...
    def emboss_filter(self, **kwargs: Any) -> Any: ...
    def evaluate_training_sites(self, **kwargs: Any) -> Any: ...
    def fast_almost_gaussian_filter(self, **kwargs: Any) -> Any: ...
    def flip_image(self, **kwargs: Any) -> Any: ...
    def frangi_filter(self, **kwargs: Any) -> Any: ...
    def frost_filter(self, **kwargs: Any) -> Any: ...
    def fuzzy_knn_classification(self, **kwargs: Any) -> Any: ...
    def gabor_filter_bank(self, **kwargs: Any) -> Any: ...
    def gamma_correction(self, **kwargs: Any) -> Any: ...
    def gamma_map_filter(self, **kwargs: Any) -> Any: ...
    def gaussian_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def generalize_classified_raster(self, **kwargs: Any) -> Any: ...
    def generalize_with_similarity(self, **kwargs: Any) -> Any: ...
    def guided_filter(self, **kwargs: Any) -> Any: ...
    def high_pass_filter(self, **kwargs: Any) -> Any: ...
    def high_pass_median_filter(self, **kwargs: Any) -> Any: ...
    def histogram_equalization(self, **kwargs: Any) -> Any: ...
    def histogram_matching(self, **kwargs: Any) -> Any: ...
    def histogram_matching_two_images(self, **kwargs: Any) -> Any: ...
    def ihs_to_rgb(self, **kwargs: Any) -> Any: ...
    def image_segmentation(self, **kwargs: Any) -> Any: ...
    def image_slider(self, **kwargs: Any) -> Any: ...
    def image_stack_profile(self, **kwargs: Any) -> Any: ...
    def integral_image_transform(self, **kwargs: Any) -> Any: ...
    def k_means_clustering(self, **kwargs: Any) -> Any: ...
    def k_nearest_mean_filter(self, **kwargs: Any) -> Any: ...
    def knn_classification(self, **kwargs: Any) -> Any: ...
    def knn_regression(self, **kwargs: Any) -> Any: ...
    def kuan_filter(self, **kwargs: Any) -> Any: ...
    def kuwahara_filter(self, **kwargs: Any) -> Any: ...
    def laplacian_filter(self, **kwargs: Any) -> Any: ...
    def laplacian_of_gaussians_filter(self, **kwargs: Any) -> Any: ...
    def lee_filter(self, **kwargs: Any) -> Any: ...
    def line_detection_filter(self, **kwargs: Any) -> Any: ...
    def line_thinning(self, **kwargs: Any) -> Any: ...
    def logistic_regression(self, **kwargs: Any) -> Any: ...
    def majority_filter(self, **kwargs: Any) -> Any: ...
    def maximum_filter(self, **kwargs: Any) -> Any: ...
    def mean_filter(self, **kwargs: Any) -> Any: ...
    def median_filter(self, **kwargs: Any) -> Any: ...
    def min_dist_classification(self, **kwargs: Any) -> Any: ...
    def min_max_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def minimum_filter(self, **kwargs: Any) -> Any: ...
    def modified_k_means_clustering(self, **kwargs: Any) -> Any: ...
    def mosaic(self, **kwargs: Any) -> Any: ...
    def mosaic_with_feathering(self, **kwargs: Any) -> Any: ...
    def nnd_classification(self, **kwargs: Any) -> Any: ...
    def non_local_means_filter(self, **kwargs: Any) -> Any: ...
    def normalized_difference_index(self, **kwargs: Any) -> Any: ...
    def olympic_filter(self, **kwargs: Any) -> Any: ...
    def opening(self, **kwargs: Any) -> Any: ...
    def otsu_thresholding(self, **kwargs: Any) -> Any: ...
    def panchromatic_sharpening(self, **kwargs: Any) -> Any: ...
    def parallelepiped_classification(self, **kwargs: Any) -> Any: ...
    def percentage_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def percentile_filter(self, **kwargs: Any) -> Any: ...
    def piecewise_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def prewitt_filter(self, **kwargs: Any) -> Any: ...
    def random_forest_classification(self, **kwargs: Any) -> Any: ...
    def random_forest_regression(self, **kwargs: Any) -> Any: ...
    def range_filter(self, **kwargs: Any) -> Any: ...
    def remove_spurs(self, **kwargs: Any) -> Any: ...
    def resample(self, **kwargs: Any) -> Any: ...
    def rgb_to_ihs(self, **kwargs: Any) -> Any: ...
    def roberts_cross_filter(self, **kwargs: Any) -> Any: ...
    def savitzky_golay_2d_filter(self, **kwargs: Any) -> Any: ...
    def scharr_filter(self, **kwargs: Any) -> Any: ...
    def sigmoidal_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def sobel_filter(self, **kwargs: Any) -> Any: ...
    def split_colour_composite(self, **kwargs: Any) -> Any: ...
    def standard_deviation_contrast_stretch(self, **kwargs: Any) -> Any: ...
    def standard_deviation_filter(self, **kwargs: Any) -> Any: ...
    def svm_classification(self, **kwargs: Any) -> Any: ...
    def svm_regression(self, **kwargs: Any) -> Any: ...
    def thicken_raster_line(self, **kwargs: Any) -> Any: ...
    def tophat_transform(self, **kwargs: Any) -> Any: ...
    def total_filter(self, **kwargs: Any) -> Any: ...
    def unsharp_masking(self, **kwargs: Any) -> Any: ...
    def user_defined_weights_filter(self, **kwargs: Any) -> Any: ...
    def wiener_filter(self, **kwargs: Any) -> Any: ...
    def write_function_memory_insertion(self, **kwargs: Any) -> Any: ...

class WbPrecisionAgricultureDomain(WbDomainNamespace):
    ...

class WbGeomorphometryDomain(WbDomainNamespace):
    def accumulation_curvature(self, **kwargs: Any) -> Any: ...
    def aspect(self, **kwargs: Any) -> Any: ...
    def average_normal_vector_angular_deviation(self, **kwargs: Any) -> Any: ...
    def casorati_curvature(self, **kwargs: Any) -> Any: ...
    def circular_variance_of_aspect(self, **kwargs: Any) -> Any: ...
    def contours_from_points(self, **kwargs: Any) -> Any: ...
    def contours_from_raster(self, **kwargs: Any) -> Any: ...
    def convergence_index(self, **kwargs: Any) -> Any: ...
    def curvedness(self, **kwargs: Any) -> Any: ...
    def deviation_from_mean_elevation(self, **kwargs: Any) -> Any: ...
    def difference_curvature(self, **kwargs: Any) -> Any: ...
    def difference_from_mean_elevation(self, **kwargs: Any) -> Any: ...
    def directional_relief(self, **kwargs: Any) -> Any: ...
    def downslope_index(self, **kwargs: Any) -> Any: ...
    def edge_density(self, **kwargs: Any) -> Any: ...
    def elev_above_pit(self, **kwargs: Any) -> Any: ...
    def elev_above_pit_dist(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_min_max(self, **kwargs: Any) -> Any: ...
    def elev_relative_to_watershed_min_max(self, **kwargs: Any) -> Any: ...
    def elevation_percentile(self, **kwargs: Any) -> Any: ...
    def embankment_mapping(self, **kwargs: Any) -> Any: ...
    def exposure_towards_wind_flux(self, **kwargs: Any) -> Any: ...
    def feature_preserving_smoothing(self, **kwargs: Any) -> Any: ...
    def fetch_analysis(self, **kwargs: Any) -> Any: ...
    def fill_missing_data(self, **kwargs: Any) -> Any: ...
    def find_ridges(self, **kwargs: Any) -> Any: ...
    def gaussian_curvature(self, **kwargs: Any) -> Any: ...
    def generating_function(self, **kwargs: Any) -> Any: ...
    def geomorphons(self, **kwargs: Any) -> Any: ...
    def hillshade(self, **kwargs: Any) -> Any: ...
    def horizon_angle(self, **kwargs: Any) -> Any: ...
    def horizontal_excess_curvature(self, **kwargs: Any) -> Any: ...
    def horton_ratios(self, **kwargs: Any) -> Any: ...
    def hypsometric_analysis(self, **kwargs: Any) -> Any: ...
    def hypsometrically_tinted_hillshade(self, **kwargs: Any) -> Any: ...
    def map_off_terrain_objects(self, **kwargs: Any) -> Any: ...
    def max_anisotropy_dev(self, **kwargs: Any) -> Any: ...
    def max_anisotropy_dev_signature(self, **kwargs: Any) -> Any: ...
    def max_branch_length(self, **kwargs: Any) -> Any: ...
    def max_difference_from_mean(self, **kwargs: Any) -> Any: ...
    def max_downslope_elev_change(self, **kwargs: Any) -> Any: ...
    def max_elev_dev_signature(self, **kwargs: Any) -> Any: ...
    def max_elevation_deviation(self, **kwargs: Any) -> Any: ...
    def max_upslope_elev_change(self, **kwargs: Any) -> Any: ...
    def maximal_curvature(self, **kwargs: Any) -> Any: ...
    def mean_curvature(self, **kwargs: Any) -> Any: ...
    def min_downslope_elev_change(self, **kwargs: Any) -> Any: ...
    def minimal_curvature(self, **kwargs: Any) -> Any: ...
    def multidirectional_hillshade(self, **kwargs: Any) -> Any: ...
    def multiscale_elevated_index(self, **kwargs: Any) -> Any: ...
    def multiscale_elevation_percentile(self, **kwargs: Any) -> Any: ...
    def multiscale_low_lying_index(self, **kwargs: Any) -> Any: ...
    def multiscale_roughness(self, **kwargs: Any) -> Any: ...
    def multiscale_roughness_signature(self, **kwargs: Any) -> Any: ...
    def multiscale_std_dev_normals(self, **kwargs: Any) -> Any: ...
    def multiscale_std_dev_normals_signature(self, **kwargs: Any) -> Any: ...
    def multiscale_topographic_position_image(self, **kwargs: Any) -> Any: ...
    def num_downslope_neighbours(self, **kwargs: Any) -> Any: ...
    def num_upslope_neighbours(self, **kwargs: Any) -> Any: ...
    def openness(self, **kwargs: Any) -> Any: ...
    def pennock_landform_classification(self, **kwargs: Any) -> Any: ...
    def percent_elev_range(self, **kwargs: Any) -> Any: ...
    def plan_curvature(self, **kwargs: Any) -> Any: ...
    def principal_curvature_direction(self, **kwargs: Any) -> Any: ...
    def profile(self, **kwargs: Any) -> Any: ...
    def profile_curvature(self, **kwargs: Any) -> Any: ...
    def relative_aspect(self, **kwargs: Any) -> Any: ...
    def relative_stream_power_index(self, **kwargs: Any) -> Any: ...
    def relative_topographic_position(self, **kwargs: Any) -> Any: ...
    def remove_off_terrain_objects(self, **kwargs: Any) -> Any: ...
    def ring_curvature(self, **kwargs: Any) -> Any: ...
    def rotor(self, **kwargs: Any) -> Any: ...
    def ruggedness_index(self, **kwargs: Any) -> Any: ...
    def sediment_transport_index(self, **kwargs: Any) -> Any: ...
    def shape_index(self, **kwargs: Any) -> Any: ...
    def sky_view_factor(self, **kwargs: Any) -> Any: ...
    def slope(self, **kwargs: Any) -> Any: ...
    def slope_vs_elev_plot(self, **kwargs: Any) -> Any: ...
    def spherical_std_dev_of_normals(self, **kwargs: Any) -> Any: ...
    def standard_deviation_of_slope(self, **kwargs: Any) -> Any: ...
    def surface_area_ratio(self, **kwargs: Any) -> Any: ...
    def tangential_curvature(self, **kwargs: Any) -> Any: ...
    def time_in_daylight(self, **kwargs: Any) -> Any: ...
    def total_curvature(self, **kwargs: Any) -> Any: ...
    def unsphericity(self, **kwargs: Any) -> Any: ...
    def vertical_excess_curvature(self, **kwargs: Any) -> Any: ...
    def viewshed(self, **kwargs: Any) -> Any: ...
    def visibility_index(self, **kwargs: Any) -> Any: ...
    def wetness_index(self, **kwargs: Any) -> Any: ...

# END GENERATED CATEGORY/DOMAIN STUBS


def list_tools_json() -> Any: ...
def list_tools() -> Any: ...
def list_tools_json_with_options(include_pro: Any = False, tier: Any = 'open') -> Any: ...
def list_tools_with_options(include_pro: Any = False, tier: Any = 'open') -> Any: ...
def list_tools_json_with_entitlement_options(signed_entitlement_json: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
def list_tools_json_with_entitlement_file_options(entitlement_file: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
def run_tool_json(tool_id: Any, args_json: Any) -> Any: ...
def run_tool(tool_id: Any, args: Any) -> Any: ...
def run_tool_json_with_progress(tool_id: Any, args_json: Any) -> Any: ...
def run_tool_json_stream(tool_id: Any, args_json: Any, callback: Any) -> Any: ...
def run_tool_stream(tool_id: Any, args: Any, callback: Any) -> Any: ...
def run_tool_json_with_options(tool_id: Any, args_json: Any, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def run_tool_json_with_entitlement_options(tool_id: Any, args_json: Any, signed_entitlement_json: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
def run_tool_json_with_entitlement_file_options(tool_id: Any, args_json: Any, entitlement_file: Any, public_key_kid: Any, public_key_b64url: Any, include_pro: Any = False, fallback_tier: Any = 'open') -> Any: ...
def run_tool_with_options(tool_id: Any, args: Any, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def run_tool_json_with_progress_options(tool_id: Any, args_json: Any, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def run_tool_json_stream_options(tool_id: Any, args_json: Any, callback: Any, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def run_tool_stream_options(tool_id: Any, args: Any, callback: Any, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def generate_wrapper_stubs_json(include_pro: Any = False, tier: Any = 'open', target: Any = 'python') -> Any: ...
def whitebox_tools(floating_license_id: Any = None, include_pro: Any = None, tier: Any = 'open', provider_url: Any = None, machine_id: Any = None, customer_id: Any = None) -> Any: ...
def abs(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def ceil(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def floor(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def round(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def sqrt(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def square(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def ln(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def log10(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def sin(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
def cos(input: Any, output: Any = None, callback: Any = None, include_pro: Any = False, tier: Any = 'open') -> Any: ...
